#                   SM64Net - An Internet framework for SM64
#                     Copyright (C) 2019 - 2021  devwizard
#         This project is licensed under the terms of the GNU General
#         Public License version 2.  See LICENSE for more information.

build/main.z64:
build/main.elf: build/UNSME0.o build/hook_a.o build/hook_b.o build/hook_c.o
build/main.elf: build/usb.o

FLAG    := -I ../include
include ../include/sm64.mak
